name: Weekly Model Training and CI/CD

on:
  schedule:
    # Run at 01:10 AM every week
    - cron: '10 1 * * 0'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  workflows: write  # Enable triggering other workflows

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        env:
            EVIDENTLY_TOKEN: ${{ secrets.EVIDENTLY_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_DEFAULT_REGION
            python src/models/train_model.py

  trigger-ci-cd:
    needs: retrain-model
    runs-on: ubuntu-latest
    steps:
      - name: Trigger air_quality_ci_cd Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'air_quality_ci_cd.yml',
              ref: context.ref.replace('refs/heads/', ''),  
            })
